class ResponseCode:
    OK = 0
    INVALID_TRANSACTION = 1
    PAYER_ACCOUNT_NOT_FOUND = 2
    INVALID_NODE_ACCOUNT = 3
    TRANSACTION_EXPIRED = 4
    INVALID_TRANSACTION_START = 5
    INVALID_TRANSACTION_DURATION = 6
    INVALID_SIGNATURE = 7
    MEMO_TOO_LONG = 8
    INSUFFICIENT_TX_FEE = 9
    INSUFFICIENT_PAYER_BALANCE = 10
    DUPLICATE_TRANSACTION = 11
    BUSY = 12
    NOT_SUPPORTED = 13
    INVALID_FILE_ID = 14
    INVALID_ACCOUNT_ID = 15
    INVALID_CONTRACT_ID = 16
    INVALID_TRANSACTION_ID = 17
    RECEIPT_NOT_FOUND = 18
    RECORD_NOT_FOUND = 19
    INVALID_SOLIDITY_ID = 20
    UNKNOWN = 21
    SUCCESS = 22

    _code_to_name = {
        0: "OK",
        1: "INVALID_TRANSACTION",
        2: "PAYER_ACCOUNT_NOT_FOUND",
        3: "INVALID_NODE_ACCOUNT",
        4: "TRANSACTION_EXPIRED",
        5: "INVALID_TRANSACTION_START",
        6: "INVALID_TRANSACTION_DURATION",
        7: "INVALID_SIGNATURE",
        8: "MEMO_TOO_LONG",
        9: "INSUFFICIENT_TX_FEE",
        10: "INSUFFICIENT_PAYER_BALANCE",
        11: "DUPLICATE_TRANSACTION",
        12: "BUSY",
        13: "NOT_SUPPORTED",
        14: "INVALID_FILE_ID",
        15: "INVALID_ACCOUNT_ID",
        16: "INVALID_CONTRACT_ID",
        17: "INVALID_TRANSACTION_ID",
        18: "RECEIPT_NOT_FOUND",
        19: "RECORD_NOT_FOUND",
        20: "INVALID_SOLIDITY_ID",
        21: "UNKNOWN",
        22: "SUCCESS"
    }

    @classmethod
    def get_name(cls, code):
        return cls._code_to_name.get(code, f"UNKNOWN_CODE_{code}")
